[package]
name = "nd_x86_64"
version = "0.0.1"

authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags = "2"
