[package]
name = "nd_init"
version = "0.0.1"

authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neodym-sys = { path = "../lib/neodym-sys" }
